services:
  api:
    image: sports-notifier
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7001:7001
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
